### ISSUE TITLE
It doesn't work on final Angular 2 release

### ISSUE THREAD

**Issue by psotelo** [bbottema/ng2-simple-page-scroll#10]
I always have this error

├── ng2-simple-page-scroll@1.0.3-beta 
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN ng2-simple-page-scroll@1.0.3-beta requires a peer of rxjs@5.0.0-beta.6 but none was installed.

**Comment by bbottema** [comment]
Fixed in 2.0.0
