### ISSUE TITLE
0 is falsy...

### ISSUE THREAD

**Issue by JuanMachado** [bbottema/ng2-simple-page-scroll#11]
On your `setScrollTop` function you have a condition that checks if the container exists and has `scrollTop` property. The problem is when it _does_ have that property but it equals **0**

[Said line](https://github.com/bbottema/ng2-simple-page-scroll/blob/6337bf7fbe5bef1e1e6541e868061a128521e8af/src/ng2-simple-page-scroll.directive.ts#L54)

**Comment by bbottema** [comment]
Fixed in 2.0.0
