### ISSUE TITLE
Getting pageScroll to work with Manuscripta

### ISSUE THREAD

**Issue by jxxcarlson** [bbottema/ng2-simple-page-scroll#12]
I am working on math and physics document processor -- see for example [this document](http://home.noteshareblog.io/manuscripta2c/documents/151).  I've been trying to get pageScroll to work with no success -- I think I am going to need your help. 

I have taken the following steps so far

* Installed `ng2-simple-page-scroll` per directions, with `Ng2SimplePageScrollModule.forRoot()` in `app.module`
* Implemented a preprocessor so that all anchor links have the form `<a pageScroll href="#...`

*Example from "this document":*
```
<ul class=&quot;sectlevel1&quot;>
<li><a pageScroll href=&quot;#_a_two_frequency_packet&quot;>A two-frequency packet</a></li>
<li><a pageScroll href=&quot;#_the_sinc_packet&quot;>The sinc packet</a></li>
</ul>
```

However, when I click on an anchor link, I am sent to the root of the project, which then reloads.  My setup may be a bit different than what you  describe, since documents containing anchor links are loaded on demand into the template of the component `document-component`:

[Code for document component's template @ Github:](https://github.com/jxxcarlson/manuscripta2c/blob/master/src/app/text_helpers/mathjax.directive.ts#L8)
```
<div>
  <h3 style=" color:cornflowerblue" (click)="loadParent()"> {{ getParentTitle() }}</h3>
  <h1> {{ activeDocument.title }}</h1>
  <div [textPageHeight]="200">
    <mathjax-pane  [document]="activeDocument"></mathjax-pane>
  </div>
</div>
```
The code for `mathjax-pane` is listed below.  It has an in-line template into which HTML is loaded via `{{document.rendered_text}}`.  The HTML has markup text which is processed by the mathJax directive so as to properly display equations and formulae.  Code for that directive is listed at the end.

[Code for MathJax Pane at Github:](https://github.com/jxxcarlson/manuscripta2c/blob/master/src/app/text_helpers/mathjaxpane.component.ts#L10)
```
// MathJax Pane:

import { Component, Input, ViewEncapsulation } from '@angular/core';
import { Document } from '../shared/document.model';

@Component({
  selector: 'mathjax-pane',
  template: `
  <script type="text/x-mathjax-config">
        MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
    </script>
<div class="rendered-document"  [mathJax]=document.rendered_text>{{document.rendered_text}}</div>`,
  styleUrls: ['./anypane.component.css'],
  encapsulation: ViewEncapsulation.None // .Native, .Emulated
})
export class MathJaxPane {
  @Input() document:Document;

}
```

Finally, here is the code for the MathJax directive:

[Code for MathJax directive @ Github:](https://github.com/jxxcarlson/manuscripta2c/blob/master/src/app/text_helpers/mathjax.directive.ts#L8)
```
// MathJax directive:

import {Directive, ElementRef, OnChanges, Input} from "@angular/core";
declare var MathJax: {
  Hub: {
    Queue: (param: Object[]) => void;
  }
}
@Directive({selector: '[mathJax]'})
export class MathJaxDirective implements OnChanges {
  @Input("mathJax") private texString: string = "";
  constructor(private element: ElementRef) {}
  ngOnChanges() {
    this.element.nativeElement.innerHTML = this.texString;
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.element.nativeElement]);
  }
}
```

**Comment by jxxcarlson** [comment]
I am closing this for now. I see that my HTML has been modified, mapping` "` => `&quot;`

**Comment by jxxcarlson** [comment]
I think this is still a live issue, though I have one doubt (see below).

(A) Here is the relevant part of the output of the preprocessor:

```
class="toc">
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a pageScroll href="#_a_two_frequency_packet">A two-frequency packet</a></li>
<li><a pageScroll href="#_the_sinc_packet">The sinc packet</a></li>
</ul>
```
It insures that the string `pageScroll` is inserted in anchor links. 

(B) I see exactly this text when I inspect the HTML via "elements" in Chrome dev tools.  ( I have added a pipe to ensure that the HTML is passed though unchanged to the browser.)  However,
when I copy what I see and then paste it into an editor, I see this:

```
<ul class=&quot;sectlevel1&quot;>
<li><a pageScroll href=&quot;#_a_two_frequency_packet&quot;>A two-frequency packet</a></li>
<li><a pageScroll href=&quot;#_the_sinc_packet&quot;>The sinc packet</a></li>
</ul>
``` 

(C) Later in the text one has `<h2 id="_the_sinc_packet">The sinc packet</h2>` (what I see in dev tools) or `<h2 id=&quot;_the_sinc_packet&quot;>The sinc packet</h2>` (what I see when I copy from the dev tools panel and then paste into an editor)

(D) I believe that the app is seeing the correct HTML bur I cannot be sure. In any case, clicking on an anchor link reloads the app, which is bad.

**Comment by bbottema** [comment]
A quick remark, you are using pageScroll instead of simplePageScroll as attributes it seems. pageScroll is the other scrolling project from which this is derived.

**Comment by jxxcarlson** [comment]
Ah - you are quire right.  I changed the preprocessor and now its output is an HTML string which contains the pieces
```
<ul class="sectlevel1">
<li><a simplePageScroll href="#_a_two_frequency_packet">A two-frequency packet</a></li>
<li><a simplePageScroll href="#_the_sinc_packet">The sinc packet</a></li>
</ul>
```  
and subsequently
```
<h2 id="_the_sinc_packet">The sinc packet</h2>
```
However, when I click on the anchor link 
```
<li><a simplePageScroll href="#_the_sinc_packet">The sinc packet</a></li>
```
the app reloads with `#_the_sinc_packet" in the url bar of the browser

**Comment by jxxcarlson** [comment]
Still not working -- Is it possible that ng2-simple-page-scroll is not loaded? I am using angular-cli --- I did not see specific directions for loading in that case, did not do anything for that.  Is there a way to test to see if ng2-simple-page-scroll is loaded?

**Comment by bbottema** [comment]
This doesn't seem an issue with ng2-simple-page-scroll, but rather how your application loads and bootstraps, which I can't go into of course. There could be a lot of reasons why an angular component might not be initialized properly.

To see a working demo of this however, you can check the [simple-java-mail's webapp](https://github.com/bbottema/simple-java-mail/tree/master/src/main/webapp) (hosted at [simplejavamail.org](http://www.simplejavamail.org)) which uses angular2 release with ng2-simple-page-scroll. Here it works fine in a basic configuration.
