### ISSUE TITLE
scrollTop returns 0 and setScrollTop() never completes

### ISSUE THREAD

**Issue by ms-denver** [bbottema/ng2-simple-page-scroll#2]
Is it possible to let setScrollTop() complete without having to check if scrollTop is not 0.

**Comment by bbottema** [comment]
I'm sorry, but I don't understand your problem. There is [no check](https://github.com/bbottema/ng2-simple-page-scroll/blob/master/src/ng2-simple-page-scroll.directive.ts) whether scrollTop is 0 or not.
