### ISSUE TITLE
getting a 404 Error in browser console for http://localhost:3000/ng2-simple-page-scroll

### ISSUE THREAD

**Issue by mac10046** [bbottema/ng2-simple-page-scroll#3]
hi

I imported the as per your README.md and added a directive and used it in my templateURL
In browser the page errors says

zone.js:101 GET http://localhost:3000/ng2-simple-page-scroll 404 (Not Found)

dashboard:24 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-simple-page-scroll(…)

here's my code:

```
import { SimplePageScroll } from 'ng2-simple-page-scroll';

@Component({
    selector: 'fund',
    directives: [SimplePageScroll],
    providers: [HttpService, sharedService],
    templateUrl: 'app/template/fund.component.html'
})
```

In app.component.html:
 

```
 <a simplePageScroll  href="#" class="sidebar-open-button"><i class="fa fa-bars"></i></a>
  <a simplePageScroll href="#" class="sidebar-open-button-mobile"><i class="fa fa-bars"></i></a>
```

**Comment by mac10046** [comment]
basically I am getting the path wrong ... but can you please guide me to get correct ... Because what I am trying is not working yet

**Comment by morocarlo** [comment]
if you are using system.config.js add ng2-simple-page-scroll': 'node_modules/ng2-simple-page-scroll', in map variable
`
var map = {
        'ng2-simple-page-scroll': 'node_modules/ng2-simple-page-scroll',
    };
`

**Comment by bbottema** [comment]
@mac10046 Does this solve it for you?
