### ISSUE TITLE
Update to Angular 2 rc.6

### ISSUE THREAD

**Issue by aamir1995** [bbottema/ng2-simple-page-scroll#7]
Hi,
Can you please update the code to work with latest Angular 2 rc.6 and router 3.0.0-rc.2. Thanks :)

**Comment by bbottema** [comment]
I've been too busy recently. I think I'll have it done within two weeks. You can also send a pull-request if you feel adventurous.

**Comment by bbottema** [comment]
Will be solved by #9.
